export const theme = {
    purplePrimary: '#6236e8',
    purpleLighter: '#825fec',
    blueDarker: '#172c4f',
    bluePrimary: '#1b335b',
    blueLighter: '#2f579d',
    greenPrimary: '#006400',
    redPrimary: '#8b0000',
    whiteLighter: '#f4f0ee',
    whiteLightest: '#fafafa',

    fontSizexxxxLargeRem: '2rem',
    fontSizexxxLargeRem: '1.5rem',
    fontSizexxLargeRem: '1.3rem',
    fontSizexLargeRem: '1.2rem',
    fontSizeLargeRem: '1.1rem',
    fontSizeRegRem: '1rem',
    fontSizeSmallRem: '0.9rem',
    fontSizexSmallRem: '0.8rem',
    fontSizexxSmallRem: '0.7rem',
    fontSizexxxSmallRem: '0.6rem',

    spaceBlockxxxxLargeRem: '2rem',
    spaceBlockxxxLargeRem: '1.5rem',
    spaceBlockxLargeRem: '1.3rem',
    spaceBlockLargeRem: '1.2rem',
    spaceBlockRegularRem: '1rem',
    spaceBlockSmallRem: '0.8rem',
    spaceBlockxSmallRem: '0.7rem',
    spaceBlockxxSmallRem: '0.6rem',
    spaceBlockxxxSmallRem: '0.5rem',

    spaceInlineRegularRem: '1rem',
    spaceInlineSmallRem: '0.8rem',
    spaceInlinexSmallRem: '0.7rem',
    spaceInlinexxSmallRem: '0.6rem',
    spaceInlinexxxSmallRem: '0.5rem',

    typographyEmphasis: 'roboto',
}